title: GayoHub
description: Kopi Gayo Khas Nusantara

url: https://long-haul.netlify.app
# Only necessary when hosting your site in a sub-directory. Project sites hosted on GitHub Pages are the common use-case of this variable.
baseurl: "/GayoHub"
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /
    - title: About
      url: /about/
    - title: Contact
      url: /contact/

social:
    github: felixnavidaz
    twitter: 
    facebook: 
    email: manullangfelix12@gmail.com
    linkedin: 
    youtube: Felix
    tumblr: 

google_analytics: "UA-58263416-1"

disqus:
    shortname: brianmaierjr
